name: boggle # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Boggle is a word game where you try to make as many words as you can
description: |
   Boggle is a word game in which players try to find as many words as they can from a grid of lettered dice, within a set time limit. It was invented by Allan Turoff and originally distributed by Parker Brothers.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  boggle_icon.png
title: Boggle

apps:
  boggle:
    command: boggle
parts:
  boggle:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      boggle: build/
      boggle.1: man/man1/

architectures:
  - build-on: amd64

